spring:
  server:
    forward-headers-strategy: framework
  config:
    import: optional:file:.env[.yml]

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}   # create-drop, create, none, validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: ${JPA_DIALECT}

  sql:
    init:
      mode: always

  #    data:
  #      redis:
  #        host: ${REDIS_HOST}
  #        port: ${REDIS_PORT}
  #        password: ${REDIS_PASSWORD}
  #        timeout: ${REDIS_TIMEOUT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_PW}
            redirect-uri: ${custom.cors.backend-origin}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
          kakao:
            client-name: Kakao
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: ${custom.cors.backend-origin}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - account_email
          naver:
            client-name: naver
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_PW}
            redirect-uri: ${custom.cors.backend-origin}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

custom:
  cors:
    allowed-origin: ${FRONT_BASE_URL}
    local-allowed-origin: ${LOCAL_FRONT_BASE_URL}
    backend-origin: ${BACK_BASE_URL}
  jwt:
    token-validity-time: # 초 단위
      access: ${ACCESS_TOKEN_TTL}
      refresh: ${REFRESH_TOKEN_TTL}
    secret: ${JWT_SECRET}
    redirect-login-success: ${custom.cors.allowed-origin}/auth/callback
  retry:
    max-delay: ${MAX_DELAY}
    max-attempts: ${MAX_ATTEMPTS}
    multiplier: ${MULTIPLIER}
aws:
  credentials:
    AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
    AWS_SECRET_KEY: ${AWS_SECRET_KEY}
    AWS_BASE_URL: ${AWS_BASE_URL}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    path: ${AWS_S3_PATH}
    exp-min: ${AWS_S3_PRESIGN_EXP}

toss:
  secret-key: ${TOSS_SECRET_KEY}
  client-key: ${TOSS_CLIENT_KEY}

logging:
  root: INFO
server:
  port: ${SERVER_PORT}

discord:
  bot:
    token: ${DISCORD_BOT_TOKEN}
    channel: ${DISCORD_CHANNEL_ID}