spring:
  config:
    import: optional:file:.env[.yml]
  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # 개발 시: create, 운영 시: validate 또는 none 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}
#      timeout: 5000

custom:
  jwt:
    redirection:
      base: ${JWT_REDIRECT_BASE}
    exp-time:
      access: ${JWT_EXP_ACCESS}
      refresh: ${JWT_EXP_REFRESH}
    secrets:
      originkey: ${JWT_ORIGIN_KEY}
      appkey: ${JWT_APP_KEY}

toss:
  secret-key: ${TOSS_SECRET_KEY}
  client-key: ${TOSS_CLIENT_KEY}

logging:
  level:
    root: INFO

server:
  port: ${SERVER_PORT}

